#!/bin/bash
echo "Installerer Wordpress..."
yum install -y epel-release
rpm -Uvh https://mirror.webtatic.com/yum/el7/webtatic-release.rpm
yum install -y php72w php72w-mysql httpd mariadb-server wget nano unzip
systemctl enable httpd
systemctl enable mariadb
systemctl start httpd
systemctl start mariadb
cd /var/www/html
mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'wpuser'@'localhost' IDENTIFIED BY 'Hgf6734djf458lhj345lkhrfelgkh34op59786fjk';"
mysql -e "flush privileges;"
mysql -e "create database wordpress;"
wget https://wordpress.org/latest.tar.gz
gunzip latest.tar.gz
tar -xf latest.tar
rm latest.tar
cd wordpress
cp wp-config-sample.php wp-config.php
sed -i 's/database_name_here/wordpress/g' wp-config.php
sed -i 's/username_here/wpuser/g' wp-config.php
sed -i 's/password_here/Hgf6734djf458lhj345lkhrfelgkh34op59786fjk/g' wp-config.php
wp-cli
curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
chmod +x wp-cli.phar
mv wp-cli.phar /usr/local/bin/wp
systemctl restart httpd
echo "Ferdig."